version: "3"

services:
    web:                       
        container_name: react-nginx-local-container                                                  
        build: 
            dockerfile: Dockerfile-LOCAL
            context: ./

        restart: always

        ports:                                       
            - 8000:80

        logging:
            options:
                max-size: "1m"
                max-file: "2"
        
        