FROM node:alpine
WORKDIR /home/src/app
COPY . .
RUN npm install
RUN npm run build:dev
# RUN npm run build:staging
# RUN npm run build:production
# RUN npm install -g serve
# CMD ["serve", "-s", "build", "-l", "tcp://0.0.0.0:5000"]